---
title: "EDA"
output: github_document
date: "2025-10-05"
---

```{r setup, include = FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


Import the weather dataset

```{r}
data("weather_df")

weather_df = 
  weather_df |> 
  mutate(
    month = floor_date(date, unit = "month")
  )
```

Make plots:

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) +
  geom_histogram()
```

Check on extreme values:

```{r}
weather_df |> 
  filter(prcp > 1000)
```

Look at data again

```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point()
```


## Add groups

```{r}
weather_df |> 
  group_by(name, month)
```

Group and count things

```{r}
weather_df |> 
  group_by(name) |> 
  summarize(
    n = n()
  )
```

```{r}
weather_df |> 
  group_by(month) |> 
  summarize(
    n = n_distinct(date)
  )
```

You can count directly

```{r}
weather_df |> 
  count(name)
```

## more interesting summaries

compute some extra stuff

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  )
```

This is still a dataframe

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |> 
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
  geom_point() +
  geom_line()
```

Sometimes format results more nicely

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |> 
  knitr::kable(digits = 2)
```

## mutate with groups


```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    center_tamx = tmax - mean_tmax
  ) |> 
  ggplot(aes(x = date, y = center_tamx, color = name)) + 
  geom_point()
```


Look for cold days

```{r}
weather_df |> 
  group_by(name, month) |> 
  mutate(
    temp_rank = min_rank(tmax) 
  ) |> 
  filter(temp_rank < 2)
```

```{r}
weather_df |> 
  group_by(name, month) |> 
  mutate(
    temp_rank = min_rank(desc(tmin)) 
  ) |> 
  filter(temp_rank < 2)
```


What about lags?

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(lagged_max = lag(tmax))
```

Use the variables create

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    temp_change = tmax - lag(tmax)
  ) |> 
  summarize(
    sd_tmax_change = sd(temp_change, na.rm = TRUE),
    tmax_change_max = max(temp_change, na.rm = TRUE)
  )
```

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    temp_change = tmax - lag(tmax),
    change_rank = min_rank(desc(temp_change))
  ) |> 
  filter(
    change_rank < 2
  )
```


```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) |> 
  mutate(visit = fct_inorder(visit))

pulse_df |> 
  group_by(visit) |> 
  summarize(
    median_bdi = median(bdi, na.rm = TRUE),
    mean_bdi = mean(bdi, na.rm = TRUE)
  ) |> 
  knitr::kable(digits = 2)
```


